### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by xx7y7xx** [xxd3vin/nw-helloworld#1]
```
➜  nw-helloworld git:(master) ✗ npm start

> nw-helloworld@1.0.0 start /Users/devin.chenyang/source/github/xxd3vin/nw-helloworld
> run --x86 --mirror https://dl.nwjs.io/ .

Fetching NW.js binary... { platform: 'darwin',
  arch: 'ia32',
  version: '0.28.3',
  flavor: 'sdk' }

[=================---------------------------------] 0.00KB/s 0.0sError: ERROR_STATUS_CODE statusCode = 404
    at Request._callback (/Users/devin.chenyang/source/github/xxd3vin/nw-helloworld/node_modules/nwjs-builder-phoenix/src/lib/common/DownloaderBase.ts:173:31)
    at Request.self.callback (/Users/devin.chenyang/source/github/xxd3vin/nw-helloworld/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/Users/devin.chenyang/source/github/xxd3vin/nw-helloworld/node_modules/request/request.js:1163:10)
    at emitOne (events.js:121:20)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/Users/devin.chenyang/source/github/xxd3vin/nw-helloworld/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! nw-helloworld@1.0.0 start: `run --x86 --mirror https://dl.nwjs.io/ .`
npm ERR! Exit status 255
npm ERR!
npm ERR! Failed at the nw-helloworld@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by xx7y7xx** [comment]
Maybe https://github.com/evshiron/nwjs-builder-phoenix/issues/40
